version: "3.7"

services:
  express-js:
    container_name: ${EXPRESS_JS_NAME}
    build:
      context: ${PROJECT_PATH}/vote-dapp-back/ #local Dockerfile
    ports:
      - ${EXPRESS_PORT}:3000
    environment:
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production
    depends_on:
      - ${MONGO_NAME}
