version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: ${MONGO_NAME} #necessary for mongo-express to connect
    volumes: #linking internal storage to the local volume
      - mongodb-data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  mongo-express:
    image: mongo-express:latest
    container_name: ${MONGO_EXPRESS_NAME}
    ports: #access mongo-express from localhost:8081
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - ${MONGO_NAME}

  express-js:
    container_name: ${EXPRESS_JS_NAME}
    build:
      context: ${PROJECT_PATH}/vote-dapp-back/ #local Dockerfile
    ports:
      - ${EXPRESS_PORT}:3000
    environment:
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_PORT=${MONGO_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production
    depends_on:
      - ${MONGO_NAME}

volumes: #creating a local docker volume for the mongodb data to persist in case of container restart
  mongodb-data:
